
import React, { useState, useMemo, useEffect, useRef } from 'react';
import { 
  Sun, 
  Compass, 
  Sparkles, 
  Moon
} from 'lucide-react';
import { differenceInDays, differenceInMonths, addYears, differenceInYears } from 'date-fns';
import { domToPng } from 'modern-screenshot';

// Firebase Imports
import { 
  onAuthStateChanged, 
  signOut,
  signInWithEmailAndPassword,
  createUserWithEmailAndPassword,
  GoogleAuthProvider,
  signInWithPopup
} from 'firebase/auth';
import { 
  collection, 
  addDoc, 
  deleteDoc, 
  doc, 
  onSnapshot, 
  setDoc,
  Timestamp,
  getDoc
} from 'firebase/firestore';
import { db, auth } from './firebase';

// Types & Constants
import { LifeGoal, FutureLetter, User, Stats, Certificate, OperationType } from './src/types';
import { MAX_AGE_YEARS, TOTAL_MONTHS } from './src/constants';

// Components
import { ErrorBoundary } from './src/components/ErrorBoundary';
import { Header } from './src/components/Header';
import { LoadingState } from './src/components/LoadingState';
import { EmptyState } from './src/components/EmptyState';
import { MiniStatCard } from './src/components/UIComponents';
import { LifeGrid } from './src/components/LifeGrid';
import { GoalList } from './src/components/GoalList';
import { LetterSection } from './src/components/LetterSection';
import { WritingLetterModal } from './src/components/WritingLetterModal';
import { CertificateModal } from './src/components/CertificateModal';
import { ReminderModal } from './src/components/ReminderModal';
import { AuthModals } from './src/components/AuthModals';
import { DeleteConfirmModal } from './src/components/DeleteConfirmModal';
import { ImagePreviewModal } from './src/components/ImagePreviewModal';

const App: React.FC = () => {
  // --- State ---
  const [birthDate, setBirthDate] = useState<string>('');
  const [goals, setGoals] = useState<LifeGoal[]>([]);
  const [letters, setLetters] = useState<FutureLetter[]>([]);
  const [user, setUser] = useState<User | null>(null);
  const [isAuthReady, setIsAuthReady] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  // UI State
  const [isLoginModalOpen, setIsLoginModalOpen] = useState(false);
  const [isOnboardingModalOpen, setIsOnboardingModalOpen] = useState(false);
  const [isWritingLetter, setIsWritingLetter] = useState(false);
  const [isCertificateModalOpen, setIsCertificateModalOpen] = useState(false);
  const [isReminderModalOpen, setIsReminderModalOpen] = useState(false);
  const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = useState(false);
  const [isImagePreviewOpen, setIsImagePreviewOpen] = useState(false);
  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
  
  // Form State
  const [newGoalTitle, setNewGoalTitle] = useState('');
  const [newGoalAge, setNewGoalAge] = useState<number | ''>('');
  const [goalError, setGoalError] = useState('');
  const [newLetterContent, setNewLetterContent] = useState('');
  const [newLetterAge, setNewLetterAge] = useState<number | ''>('');
  const [newCenturyLetterContent, setNewCenturyLetterContent] = useState('');
  const [letterError, setLetterError] = useState('');
  const [onboardingName, setOnboardingName] = useState('');
  const [loginEmail, setLoginEmail] = useState('');
  const [loginPassword, setLoginPassword] = useState('');
  const [loginError, setLoginError] = useState<string | null>(null);
  const [isLoggingIn, setIsLoggingIn] = useState(false);
  const [isUpdatingName, setIsUpdatingName] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSubmittingReminder, setIsSubmittingReminder] = useState(false);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);
  
  // Data State
  const [pendingLetter, setPendingLetter] = useState<{ content: string; age: number } | null>(null);
  const [certificateData, setCertificateData] = useState<Certificate | null>(null);
  const [allCertificates, setAllCertificates] = useState<Certificate[]>([]);
  const [currentCertificateIndex, setCurrentCertificateIndex] = useState(0);
  const [goalToDeleteId, setGoalToDeleteId] = useState<string | null>(null);
  const [letterToDeleteId, setLetterToDeleteId] = useState<string | null>(null);
  const [downloadedImage, setDownloadedImage] = useState<string | null>(null);
  const [autoGeneratedCertImage, setAutoGeneratedCertImage] = useState<string | null>(null);
  const [isEditingCertificateName, setIsEditingCertificateName] = useState(false);

  const certificateRef = useRef<HTMLDivElement>(null);

  // --- Effects ---
  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, async (firebaseUser) => {
      if (firebaseUser) {
        const userDoc = await getDoc(doc(db, 'users', firebaseUser.uid));
        const userData = userDoc.data();
        
        setUser({
          id: firebaseUser.uid,
          email: firebaseUser.email || '',
          name: userData?.name || firebaseUser.displayName || 'Time Traveler',
          birthDate: userData?.birthDate || ''
        });

        if (userData?.birthDate) setBirthDate(userData.birthDate);
        if (!userData?.name && !firebaseUser.displayName) setIsOnboardingModalOpen(true);
      } else {
        setUser(null);
      }
      setIsAuthReady(true);
    });
    return unsubscribe;
  }, []);

  useEffect(() => {
    if (!user) {
      setGoals([]);
      setLetters([]);
      return;
    }

    const unsubGoals = onSnapshot(collection(db, 'users', user.id, 'goals'), (snapshot) => {
      setGoals(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as LifeGoal)));
    });

    const unsubLetters = onSnapshot(collection(db, 'users', user.id, 'letters'), (snapshot) => {
      setLetters(snapshot.docs.map(doc => {
        const data = doc.data();
        return {
          id: doc.id,
          content: data.content,
          age: data.unlockAge,
          date: data.createdAt?.toDate() || new Date()
        } as FutureLetter;
      }));
    });

    return () => {
      unsubGoals();
      unsubLetters();
    };
  }, [user]);

  // --- Logic ---
  const stats = useMemo(() => {
    if (!birthDate) return null;
    const birth = new Date(birthDate);
    const now = new Date();
    const daysLived = differenceInDays(now, birth);
    const monthsLived = differenceInMonths(now, birth);
    const yearsLived = differenceInYears(now, birth);
    const totalDays = MAX_AGE_YEARS * 365.25;
    const percentLived = Math.min(100, (daysLived / totalDays) * 100);

    return { daysLived, monthsLived, yearsLived, percentLived };
  }, [birthDate]);

  const goalMap = useMemo(() => {
    const map = new Map<number, LifeGoal[]>();
    goals.forEach(goal => {
      const monthIdx = goal.age * 12;
      if (!map.has(monthIdx)) map.set(monthIdx, []);
      map.get(monthIdx)?.push(goal);
    });
    return map;
  }, [goals]);

  const gridItems = useMemo(() => {
    if (!birthDate) return [];
    const items = [];
    for (let i = 0; i < TOTAL_MONTHS; i++) {
      items.push(i < (stats?.monthsLived || 0));
    }
    return items;
  }, [stats?.monthsLived, birthDate]);

  // --- Handlers ---
  const handleFirestoreError = (error: any, operation: OperationType, path: string) => {
    console.error(`Firestore ${operation} failed at ${path}:`, error);
  };

  const handleLogout = async () => {
    await signOut(auth);
    setUser(null);
    setBirthDate('');
  };

  const addGoal = async () => {
    if (!user) { setIsLoginModalOpen(true); return; }
    if (!newGoalTitle.trim() || newGoalAge === '') { setGoalError('Please fill all fields'); return; }
    try {
      await addDoc(collection(db, 'users', user.id, 'goals'), {
        title: newGoalTitle,
        age: Number(newGoalAge),
        completed: false
      });
      setNewGoalTitle('');
      setNewGoalAge('');
      setGoalError('');
    } catch (err) { handleFirestoreError(err, OperationType.CREATE, `users/${user.id}/goals`); }
  };

  const toggleGoalCompletion = async (id: string) => {
    if (!user) return;
    const goal = goals.find(g => g.id === id);
    if (!goal) return;
    try {
      await setDoc(doc(db, 'users', user.id, 'goals', id), { ...goal, completed: !goal.completed }, { merge: true });
    } catch (err) { handleFirestoreError(err, OperationType.UPDATE, `users/${user.id}/goals/${id}`); }
  };

  const removeGoal = (id: string) => {
    setGoalToDeleteId(id);
    setIsDeleteConfirmOpen(true);
  };

  const confirmDelete = async () => {
    if (!user) return;
    try {
      if (goalToDeleteId) await deleteDoc(doc(db, 'users', user.id, 'goals', goalToDeleteId));
      if (letterToDeleteId) await deleteDoc(doc(db, 'users', user.id, 'letters', letterToDeleteId));
    } catch (err) { console.error('Delete failed:', err); }
    setGoalToDeleteId(null);
    setLetterToDeleteId(null);
    setIsDeleteConfirmOpen(false);
  };

  const handleDownloadCertificate = async () => {
    if (isDownloading || !certificateRef.current) return;
    setIsDownloading(true);
    try {
      const dataUrl = await domToPng(certificateRef.current, { scale: 3 });
      setDownloadedImage(dataUrl);

      if (isMobile && navigator.share) {
        const response = await fetch(dataUrl);
        const blob = await response.blob();
        const file = new File([blob], 'LifeGrid-Certificate.png', { type: 'image/png' });
        await navigator.share({ files: [file], title: 'LifeGrid Certificate' });
      } else if (isMobile) {
        setIsImagePreviewOpen(true);
      } else {
        const link = document.createElement('a');
        link.href = dataUrl;
        link.download = 'LifeGrid-Certificate.png';
        link.click();
      }
    } catch (err) {
      console.error('Download failed:', err);
      alert('Failed to save certificate. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  const confirmLetter = async () => {
    if (!pendingLetter || !user || !birthDate) return;
    setIsSubmittingReminder(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 2200));
      const unlockDate = addYears(new Date(birthDate), pendingLetter.age);
      await addDoc(collection(db, 'users', user.id, 'letters'), {
        content: pendingLetter.content,
        unlockAge: pendingLetter.age,
        createdAt: Timestamp.now()
      });

      setCertificateData({
        id: Date.now().toString().slice(-8).toUpperCase(),
        sender: user.name,
        departureYear: new Date().getFullYear(),
        arrivalYear: unlockDate.getFullYear(),
        arrivalAge: pendingLetter.age,
        isCenturyTraveler: unlockDate.getFullYear() >= 2100,
        date: new Date()
      });

      setAllCertificates(prev => [{
        id: Date.now().toString().slice(-8).toUpperCase(),
        sender: user.name,
        departureYear: new Date().getFullYear(),
        arrivalYear: unlockDate.getFullYear(),
        arrivalAge: pendingLetter.age,
        isCenturyTraveler: unlockDate.getFullYear() >= 2100,
        date: new Date()
      }, ...prev]);

      setIsCertificateModalOpen(true);
      setIsWritingLetter(false);
      setIsReminderModalOpen(false);
      setPendingLetter(null);
    } catch (err) { console.error('Send failed:', err); }
    finally { setIsSubmittingReminder(false); }
  };

  const updateUserName = async (newName: string) => {
    if (!user || !newName.trim()) return;
    setIsUpdatingName(true);
    try {
      await setDoc(doc(db, 'users', user.id), { name: newName.trim() }, { merge: true });
      setUser({ ...user, name: newName.trim() });
      setIsOnboardingModalOpen(false);
      setIsEditingCertificateName(false);
    } catch (err) { console.error('Update name failed:', err); }
    finally { setIsUpdatingName(false); }
  };

  // --- Render ---
  if (!isAuthReady) return <LoadingState />;

  return (
    <ErrorBoundary>
      <div className="min-h-screen bg-[#FDFCFB] text-[#4A443F] flex flex-col overflow-hidden font-sans">
        <Header 
          birthDate={birthDate}
          setBirthDate={setBirthDate}
          user={user}
          isUserMenuOpen={isUserMenuOpen}
          setIsUserMenuOpen={setIsUserMenuOpen}
          allCertificates={allCertificates}
          setCurrentCertificateIndex={setCurrentCertificateIndex}
          setIsCertificateModalOpen={setIsCertificateModalOpen}
          handleLogout={handleLogout}
          setIsLoginModalOpen={setIsLoginModalOpen}
        />

        <main className="flex-1 overflow-auto p-4 md:p-8 flex flex-col max-w-7xl mx-auto w-full">
          {!birthDate ? (
            <EmptyState />
          ) : (
            <div className="flex flex-col gap-8 h-full">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 shrink-0">
                <MiniStatCard title="Days Lived" value={stats?.daysLived.toLocaleString()} icon={<Sun size={14} />} color="text-[#57534E]" />
                <MiniStatCard title="Years Passed" value={stats?.yearsLived} icon={<Compass size={14} />} color="text-[#57534E]" />
                <MiniStatCard title="Life Progress" value={`${stats?.percentLived.toFixed(1)}%`} icon={<Sparkles size={14} />} color="text-[#57534E]" />
                <MiniStatCard title="Future Seasons" value={(TOTAL_MONTHS - (stats?.monthsLived || 0)).toLocaleString()} icon={<Moon size={14} />} color="text-[#57534E]" />
              </div>

              <div className="flex flex-col lg:flex-row gap-8 flex-1 min-h-0">
                <LifeGrid 
                  birthDate={birthDate}
                  gridItems={gridItems}
                  goalMap={goalMap}
                  stats={stats}
                />

                <div className="flex-[1.5] flex flex-col gap-8 min-h-0 w-full lg:min-w-[400px]">
                  <GoalList 
                    goals={goals}
                    newGoalTitle={newGoalTitle}
                    setNewGoalTitle={setNewGoalTitle}
                    newGoalAge={newGoalAge}
                    setNewGoalAge={setNewGoalAge}
                    addGoal={addGoal}
                    goalError={goalError}
                    toggleGoalCompletion={toggleGoalCompletion}
                    removeGoal={removeGoal}
                  />

                  <LetterSection 
                    letters={letters}
                    stats={stats}
                    setIsWritingLetter={setIsWritingLetter}
                    removeLetter={(id) => { setLetterToDeleteId(id); setIsDeleteConfirmOpen(true); }}
                    openLetter={(letter) => {
                      setCertificateData({
                        id: letter.id.slice(-8).toUpperCase(),
                        sender: user?.name || 'Time Traveler',
                        departureYear: letter.date.getFullYear(),
                        arrivalYear: addYears(new Date(birthDate), letter.age).getFullYear(),
                        arrivalAge: letter.age,
                        isCenturyTraveler: addYears(new Date(birthDate), letter.age).getFullYear() >= 2100,
                        date: letter.date
                      });
                      setIsCertificateModalOpen(true);
                    }}
                  />
                </div>
              </div>
            </div>
          )}
        </main>

        {/* Modals */}
        <AuthModals 
          isLoginModalOpen={isLoginModalOpen}
          setIsLoginModalOpen={setIsLoginModalOpen}
          isOnboardingModalOpen={isOnboardingModalOpen}
          setIsOnboardingModalOpen={setIsOnboardingModalOpen}
          loginEmail={loginEmail}
          setLoginEmail={setLoginEmail}
          loginPassword={loginPassword}
          setLoginPassword={setLoginPassword}
          loginError={loginError}
          isLoggingIn={isLoggingIn}
          handleEmailLogin={(e) => { e.preventDefault(); signInWithEmailAndPassword(auth, loginEmail, loginPassword).then(() => setIsLoginModalOpen(false)); }}
          handleEmailSignUp={(e) => { e.preventDefault(); createUserWithEmailAndPassword(auth, loginEmail, loginPassword).then(() => setIsLoginModalOpen(false)); }}
          handleGoogleLogin={() => { const p = new GoogleAuthProvider(); signInWithPopup(auth, p).then(() => setIsLoginModalOpen(false)); }}
          onboardingName={onboardingName}
          setOnboardingName={setOnboardingName}
          updateUserName={updateUserName}
          isUpdatingName={isUpdatingName}
        />

        <WritingLetterModal 
          isOpen={isWritingLetter}
          onClose={() => setIsWritingLetter(false)}
          newLetterContent={newLetterContent}
          setNewLetterContent={setNewLetterContent}
          newLetterAge={newLetterAge}
          setNewLetterAge={setNewLetterAge}
          newCenturyLetterContent={newCenturyLetterContent}
          setNewCenturyLetterContent={setNewCenturyLetterContent}
          letterError={letterError}
          setLetterError={setLetterError}
          addLetter={() => {
             if (newLetterAge === '' && newCenturyLetterContent === '') { setLetterError('Please fill fields'); return; }
             setPendingLetter({ content: newLetterContent || newCenturyLetterContent, age: Number(newLetterAge) || 100 });
             setIsReminderModalOpen(true);
          }}
          stats={stats}
        />

        <CertificateModal 
          isOpen={isCertificateModalOpen}
          onClose={() => setIsCertificateModalOpen(false)}
          allCertificates={allCertificates.length > 0 ? allCertificates : (certificateData ? [certificateData] : [])}
          currentCertificateIndex={currentCertificateIndex}
          setCurrentCertificateIndex={setCurrentCertificateIndex}
          isMobile={isMobile}
          isDownloading={isDownloading}
          handleDownloadCertificate={handleDownloadCertificate}
          onboardingName={onboardingName}
          setOnboardingName={setOnboardingName}
          isEditingCertificateName={isEditingCertificateName}
          setIsEditingCertificateName={setIsEditingCertificateName}
          updateUserName={updateUserName}
          autoGeneratedCertImage={autoGeneratedCertImage}
          isAutoGenerating={isAutoGenerating}
          certificateRef={certificateRef}
        />

        <ReminderModal 
          isOpen={isReminderModalOpen}
          onClose={() => setIsReminderModalOpen(false)}
          isSubmittingReminder={isSubmittingReminder}
          pendingLetter={pendingLetter}
          user={user}
          confirmLetter={confirmLetter}
        />

        <DeleteConfirmModal 
          isOpen={isDeleteConfirmOpen}
          onClose={() => setIsDeleteConfirmOpen(false)}
          onConfirm={confirmDelete}
          title="Delete Item?"
          message="This action cannot be undone. Your data will be removed from the time tunnel."
        />

        <ImagePreviewModal 
          isOpen={isImagePreviewOpen}
          onClose={() => setIsImagePreviewOpen(false)}
          imageUrl={downloadedImage}
        />
      </div>
    </ErrorBoundary>
  );
};

export default App;
